<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ApplicationIcon>Resources\images\Alohomora_64.ico</ApplicationIcon>
    <PackageIcon>Alohomora_128.png</PackageIcon>
    <RepositoryUrl>https://github.com/MmHamzeh/Alohomora</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Resources\images\Alohomora_64.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="EasyCaching.InMemory" Version="1.9.2" />
    <PackageReference Include="MD.PersianDateTime.Standard" Version="2.6.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication" Version="2.3.12" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.11" />
    <PackageReference Include="Microsoft.AspNetCore.Authorization" Version="10.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.11">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
      <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.11" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.11">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>

    <PackageReference Include="EasyCaching.Core" Version="1.9.2" />
    <PackageReference Include="HtmlSanitizer" Version="9.2.1039" />
    <PackageReference Include="Microsoft.AspNetCore.Http" Version="2.3.12" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.12" />
    <PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.3.12" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.11" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.11" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.11" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.22.0" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Resources\images\Alohomora_128.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Domain\Models\DtoModels\ExternalModels\" />
  </ItemGroup>

</Project>
