//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alohomora.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class IdentityResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IdentityResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Alohomora.Services.Resources.IdentityResource", typeof(IdentityResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب کاربری شما به دلیل تلاش‌های ناموفق برای ورود، قفل شده است.\n لطفا بعد از {0} {1}، مجددا تلاش کنید..
        /// </summary>
        internal static string AccountLocked {
            get {
                return ResourceManager.GetString("AccountLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تلاش ناموفق برای ورود به حساب کاربری با آی‌پی {0} انجام شد.\n اگر این تلاش توسط شما نبوده، لطفا رمز عبور خود را تغییر دهید..
        /// </summary>
        internal static string InvalidLoginNotificationWithIpAddress {
            get {
                return ResourceManager.GetString("InvalidLoginNotificationWithIpAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورود به حساب کاربری با آی‌پی {0} انجام شد.\n اگر این ورود توسط شما نبوده، لطفا رمز عبور خود را تغییر دهید..
        /// </summary>
        internal static string LoginNotificationWithIpAddress {
            get {
                return ResourceManager.GetString("LoginNotificationWithIpAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد {0} را جهت ورود به سامانه وارد کنید.\n #{1}\n {2}-{3}.
        /// </summary>
        internal static string OtpMessage {
            get {
                return ResourceManager.GetString("OtpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبور شما با موفقیت تغییر یافت.\n اگر این تغییر توسط شما نبوده، لطفا رمز عبور خود را مجددا تغییر دهید..
        /// </summary>
        internal static string PasswordChangedNotification {
            get {
                return ResourceManager.GetString("PasswordChangedNotification", resourceCulture);
            }
        }
    }
}
